# Host-side embedding for uncompressed build products. This deliberately does
# not execute a target-platform tool when cross-compiling for iOS.
foreach(required INPUT OUTPUT_C OUTPUT_H SYMBOL)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "EmbedBinary requires ${required}")
    endif()
endforeach()
if(NOT SYMBOL MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
    message(FATAL_ERROR "Invalid C identifier: ${SYMBOL}")
endif()
file(SIZE "${INPUT}" size)
if(size EQUAL 0)
    message(FATAL_ERROR "Cannot embed an empty binary: ${INPUT}")
endif()
file(READ "${INPUT}" bytes HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${bytes}")
get_filename_component(c_dir "${OUTPUT_C}" DIRECTORY)
get_filename_component(h_dir "${OUTPUT_H}" DIRECTORY)
file(MAKE_DIRECTORY "${c_dir}" "${h_dir}")
file(WRITE "${OUTPUT_C}.tmp" "unsigned char ${SYMBOL}[${size}] = {${bytes}};\n")
file(WRITE "${OUTPUT_H}.tmp" "#pragma once\n#ifdef __cplusplus\nextern \"C\" {\n#endif\nextern unsigned char ${SYMBOL}[${size}];\n#ifdef __cplusplus\n}\n#endif\n")
file(RENAME "${OUTPUT_C}.tmp" "${OUTPUT_C}")
file(RENAME "${OUTPUT_H}.tmp" "${OUTPUT_H}")
