include_guard(GLOBAL)
if(POLICY CMP0205)
    cmake_policy(SET CMP0205 NEW)
endif()

# Build a patched copy, never mutate the user's dependency checkout. Only
# project sources are copied; unchanged dependency trees remain linked.
function(unleashed_prepare_dependency output name source)
    cmake_parse_arguments(ARG "" "" "PATCHES;COPY_DIRS" ${ARGN})
    find_package(Git REQUIRED)
    file(GLOB entries CONFIGURE_DEPENDS "${source}/*")
    set(inputs)
    foreach(entry IN LISTS entries)
        if(NOT IS_DIRECTORY "${entry}")
            list(APPEND inputs "${entry}")
        endif()
    endforeach()
    foreach(directory IN LISTS ARG_COPY_DIRS)
        file(GLOB_RECURSE contents CONFIGURE_DEPENDS LIST_DIRECTORIES FALSE "${source}/${directory}/*")
        list(APPEND inputs ${contents})
    endforeach()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${inputs} ${ARG_PATCHES})
    set(fingerprint "${source}")
    foreach(input IN LISTS inputs ARG_PATCHES)
        file(SHA256 "${input}" hash)
        string(APPEND fingerprint "${input}:${hash}\n")
    endforeach()
    string(SHA256 fingerprint "${fingerprint}")
    set(copy "${CMAKE_BINARY_DIR}/patched-dependencies/${name}/${fingerprint}")
    if(NOT EXISTS "${copy}/.patches-applied")
        file(REMOVE_RECURSE "${copy}")
        file(MAKE_DIRECTORY "${copy}")
        foreach(entry IN LISTS entries)
            get_filename_component(basename "${entry}" NAME)
            if(basename STREQUAL ".git")
                continue()
            endif()
            if(IS_DIRECTORY "${entry}" AND NOT basename IN_LIST ARG_COPY_DIRS)
                file(CREATE_LINK "${entry}" "${copy}/${basename}" SYMBOLIC COPY_ON_ERROR)
            else()
                file(COPY "${entry}" DESTINATION "${copy}")
            endif()
        endforeach()
        foreach(patch IN LISTS ARG_PATCHES)
            # Do not let git discover the enclosing project and silently skip
            # dependency-relative patch paths from this nested directory.
            set(apply_command "${CMAKE_COMMAND}" -E env "GIT_CEILING_DIRECTORIES=${CMAKE_BINARY_DIR}/patched-dependencies"
                "${GIT_EXECUTABLE}" apply)
            execute_process(COMMAND ${apply_command} --check "${patch}"
                WORKING_DIRECTORY "${copy}" RESULT_VARIABLE check ERROR_VARIABLE reason)
            if(check EQUAL 0)
                execute_process(COMMAND ${apply_command} "${patch}"
                    WORKING_DIRECTORY "${copy}" RESULT_VARIABLE applied ERROR_VARIABLE reason)
                if(NOT applied EQUAL 0)
                    message(FATAL_ERROR "Failed to apply ${patch} to build copy: ${reason}")
                endif()
            else()
                execute_process(COMMAND ${apply_command} --reverse --check "${patch}"
                    WORKING_DIRECTORY "${copy}" RESULT_VARIABLE reversed ERROR_QUIET)
                if(NOT reversed EQUAL 0)
                    message(FATAL_ERROR "Dependency ${name} is incompatible with ${patch}. Original checkout is untouched.\n${reason}")
                endif()
            endif()
        endforeach()
        file(WRITE "${copy}/.patches-applied" "${fingerprint}\n")
    endif()
    set(${output} "${copy}" PARENT_SCOPE)
endfunction()
